### PR TITLE
Add more tags to the navigation

### PR DESCRIPTION
**Pull request by hkdobrev**
Mostly SEO value, but also one of the winners is an office and was not represented in the menu.

### CODE REVIEW

**Comment by thomdorkings** [comment]
@hkdobrev How many images are tagged with these room types? I think we didn't include them as there wasn't enough for each?

**Comment by hkdobrev** [comment]
@thomdorkings We have at least 2 for each, 3 for hallway. And one of the winners is an office.

**Comment by thomdorkings** [comment]
I think we'll leave this for now. I'll discuss with Rose but other than SEO, I don't see a lot of benefit (how much furniture can you put in a hallway?). Is there a way to create the pages but not display links in the tags include?

**Comment by hkdobrev** [comment]
@thomdorkings It's certainly possible. We can add an `in_nav` property to tags and use for the navigation, but it would still generate the tag page and include it in the potential sitemap (#5).

**Comment by hkdobrev** [comment]
@thomdorkings To clarify you don't want these tags visible only in the main navigation or you don't want them visible in the project page either?

**Comment by thomdorkings** [comment]
@hkdobrev I don't want the tags visible in the navigation at all, but we can generate the pages so they still appear in the sitemap / via google if we feel there is SEO benefit

**Pull request closed without merging**
